# Site settings
author: Shaqqour
title: Sinatra Project
header-img: img/home-bg.png
email: mshaqqourm@gmail.com
copyright_name: Shaqqour
description: > # this means to ignore newlines until "baseurl:"
  Movie-User Library Controller
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shaqqour

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
